#!/bin/bash
# script for changing sound card 
sed -i '4s/.*/    card PCH/' $HOME/.asoundrc
sed -i '9s/.*/    card PCH/' $HOME/.asoundrc
sed -i '2s/.*/set dsp.alsa.device=plughw:0,0/' $HOME/.config/cmus/rc
